/* P6
480 229
255
*/

#include <stdio.h>
#include <stdlib.h>

int main()
{
	int w, h, max;
	int c;
	scanf("P6\n");
	scanf("%d %d\n", &w, &h);
	scanf("%d\n", &max);
	
	if (max != 255)
	{
		fprintf(stderr, "maximum wasn't 255?\n");
		abort();
	}
	
	printf("/* THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY */\n");
	printf("int image_height = %d;\n", h);
	printf("int image_width = %d;\n", w);
	printf("unsigned short image_data[] = {");
	do {
		int r = getchar();
		int g = getchar();
		int b = getchar();
		unsigned short d;
		if (r == EOF || g == EOF || b == EOF)
			break;
		
		d = 0;
		d |= (r << 8) & 0xF800;
		d |= (g << 3) & 0x07E0;
		d |= (b >> 3) & 0x001F;
		
		printf("0x%04x, ", d);
	} while(1);
	while ((c = getchar()) != EOF)
		printf("%d, ", c);
	printf("};\n");
	
	return 0;
}
